### ISSUE TITLE
启动出现了报错

### ISSUE THREAD

**Issue by yanaex** [jayqizone/homebridge-mi-heatercooler#8]
[AcPartner] { Error: Method `get_model_and_state` is not supported
    at Object.reject (/homebridge/node_modules/miio/lib/device.js:217:13)
    at Device._onMessage (/homebridge/node_modules/miio/lib/device.js:108:8)
    at Socket.emit (events.js:182:13)
    at UDP.onMessage (dgram.js:628:8) code: -10000 }
[11/25/2018, 12:59:18 AM] [homebridge-config-ui-x] Unauthorised WebSocket Connection Closed

**Comment by yanaex** [comment]
- 已解决,空调IP写错了导致无法连接
